server:
  port: 9090
  servlet:
    context-path: /

spring:
  application:
    name: rpa-robot
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:D:\\seebon/rpa/db/robot;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MySQL;AUTO_RECONNECT=TRUE;DATABASE_TO_UPPER=false
    username: robot9y
    password: robot9y
    initialization-mode: ALWAYS
    sql-script-encoding: utf-8
    schema: classpath:db/schema-h2.sql
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        trace: true
        web-allow-others: true
  jpa:
    show-sql: true

mybatis:
  type-aliases-package: com.seebon.rpa.entity
  mapper-locations: classpath:mapper/*.xml
mapper:
  mappers: com.seebon.rpa.repository.config.MybatisMapper
  not-empty: false

rpa:
  server: https://rpa.seebon.com/api
  token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiJ4dWZ1emhvdSIsInNjb3BlIjpbInJ3Il0sIm5hbWUiOiLlvpDlr4zlkagiLCJjdXN0SWQiOjEsInVzZXJUeXBlIjoxLCJtYWluVXNlciI6bnVsbCwiZXhwIjoxODA3OTM0NDMwLCJjdXN0TmFtZSI6IuW5v-W3nuWNl-aWueS7lemAmue9kee7nOenkeaKgOaciemZkOWFrOWPuCIsInVzZXJJZCI6MTYsImF1dGhvcml0aWVzIjpbImFkbWluIl0sImp0aSI6IjM4NGY4MzBjLTI0NDUtNGY3MS1iYjhhLTEyZDM0ZjAxMDQwYSIsImNsaWVudF9pZCI6InJwYSJ9.pbfYDUnIeTw3ZuGoVYsXjEDrLWiZv_j6Nly-yOK44Dk
  work-path: D:\\seebon\\rpa
  client-version: 1.0.0
  bin360: F:\\360\\360brown\\360se6\\Application\\360se.exe
  binChrome: E:\\otherSoft\\chrome-win64\\chrome.exe
  python-path: E:\\installSoft\\Python36\\python.exe
  use-hub: 0

logging:
  file:
    name: logs/app.log
  level:
    root: info

#配置开发者模式
developer:
  auto:
    sync: off
    task: off
  upset-actions: off
  mysql:
    activated: off
    url: jdbc:mysql://192.168.0.81:3306/rpa_robot_uat?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: dev
    password: 139A281**dev

setting:
  sms:
    tcp:
      server:
        port: 8234
        ip: 172.172.4.131


tax:
  client:
    city:
      mapping: '{"北京":"北京市","天津":"天津市","石家庄":"河北省","唐山":"河北省","秦皇岛":"河北省","邯郸":"河北省","邢台":"河北省","保定":"河北省","张家口":"河北省","承德":"河北省","沧州":"河北省","廊坊":"河北省","衡水":"河北省","太原":"山西省","大同":"山西省","阳泉":"山西省","长治":"山西省","晋城":"山西省","朔州":"山西省","晋中":"山西省","运城":"山西省","忻州":"山西省","临汾":"山西省","吕梁":"山西省","呼和浩特":"内蒙古自治区","包头":"内蒙古自治区","乌海":"内蒙古自治区","赤峰":"内蒙古自治区","通辽":"内蒙古自治区","鄂尔多斯":"内蒙古自治区","呼伦贝尔":"内蒙古自治区","巴彦淖尔":"内蒙古自治区","乌兰察布":"内蒙古自治区","兴安盟":"内蒙古自治区","锡林郭勒盟":"内蒙古自治区","阿拉善盟":"内蒙古自治区","沈阳":"辽宁省","大连":"大连市","鞍山":"辽宁省","抚顺":"辽宁省","本溪":"辽宁省","丹东":"辽宁省","锦州":"辽宁省","营口":"辽宁省","阜新":"辽宁省","辽阳":"辽宁省","盘锦":"辽宁省","铁岭":"辽宁省","朝阳":"辽宁省","葫芦岛":"辽宁省","长春":"吉林省","吉林":"吉林省","四平":"吉林省","辽源":"吉林省","通化":"吉林省","白山":"吉林省","松原":"吉林省","白城":"吉林省","延边":"吉林省","哈尔滨":"黑龙江省","齐齐哈尔":"黑龙江省","鸡西":"黑龙江省","鹤岗":"黑龙江省","双鸭山":"黑龙江省","大庆":"黑龙江省","伊春":"黑龙江省","佳木斯":"黑龙江省","七台河":"黑龙江省","牡丹江":"黑龙江省","黑河":"黑龙江省","绥化":"黑龙江省","大兴安岭":"黑龙江省","上海":"上海市","南京":"江苏省","无锡":"江苏省","徐州":"江苏省","常州":"江苏省","苏州":"江苏省","南通":"江苏省","连云港":"江苏省","淮安":"江苏省","盐城":"江苏省","扬州":"江苏省","镇江":"江苏省","泰州":"江苏省","宿迁":"江苏省","杭州":"浙江省","宁波":"宁波市","温州":"浙江省","嘉兴":"浙江省","湖州":"浙江省","绍兴":"浙江省","金华":"浙江省","衢州":"浙江省","舟山":"浙江省","台州":"浙江省","丽水":"浙江省","合肥":"安徽省","芜湖":"安徽省","蚌埠":"安徽省","淮南":"安徽省","马鞍山":"安徽省","淮北":"安徽省","铜陵":"安徽省","安庆":"安徽省","黄山":"安徽省","滁州":"安徽省","阜阳":"安徽省","宿州":"安徽省","六安":"安徽省","亳州":"安徽省","池州":"安徽省","宣城":"安徽省","福州":"福建省","厦门":"厦门市","莆田":"福建省","三明":"福建省","泉州":"福建省","漳州":"福建省","南平":"福建省","龙岩":"福建省","宁德":"福建省","南昌":"江西省","景德镇":"江西省","萍乡":"江西省","九江":"江西省","新余":"江西省","鹰潭":"江西省","赣州":"江西省","吉安":"江西省","宜春":"江西省","抚州":"江西省","上饶":"江西省","济南":"山东省","青岛":"青岛市","淄博":"山东省","枣庄":"山东省","东营":"山东省","烟台":"山东省","潍坊":"山东省","济宁":"山东省","泰安":"山东省","威海":"山东省","日照":"山东省","临沂":"山东省","德州":"山东省","聊城":"山东省","滨州":"山东省","菏泽":"山东省","郑州":"河南省","开封":"河南省","洛阳":"河南省","平顶山":"河南省","安阳":"河南省","鹤壁":"河南省","新乡":"河南省","焦作":"河南省","濮阳":"河南省","许昌":"河南省","漯河":"河南省","三门峡":"河南省","南阳":"河南省","商丘":"河南省","信阳":"河南省","周口":"河南省","驻马店":"河南省","武汉":"湖北省","黄石":"湖北省","十堰":"湖北省","宜昌":"湖北省","襄阳":"湖北省","鄂州":"湖北省","荆门":"湖北省","孝感":"湖北省","荆州":"湖北省","黄冈":"湖北省","咸宁":"湖北省","随州":"湖北省","恩施":"湖北省","长沙":"湖南省","株洲":"湖南省","湘潭":"湖南省","衡阳":"湖南省","邵阳":"湖南省","岳阳":"湖南省","常德":"湖南省","张家界":"湖南省","益阳":"湖南省","郴州":"湖南省","永州":"湖南省","怀化":"湖南省","娄底":"湖南省","湘西":"湖南省","广州":"广东省","韶关":"广东省","深圳":"深圳市","珠海":"广东省","汕头":"广东省","佛山":"广东省","江门":"广东省","湛江":"广东省","茂名":"广东省","肇庆":"广东省","惠州":"广东省","梅州":"广东省","汕尾":"广东省","河源":"广东省","阳江":"广东省","清远":"广东省","东莞":"广东省","中山":"广东省","潮州":"广东省","揭阳":"广东省","云浮":"广东省","南宁":"广西壮族自治区","柳州":"广西壮族自治区","桂林":"广西壮族自治区","梧州":"广西壮族自治区","北海":"广西壮族自治区","防城港":"广西壮族自治区","钦州":"广西壮族自治区","贵港":"广西壮族自治区","玉林":"广西壮族自治区","百色":"广西壮族自治区","贺州":"广西壮族自治区","河池":"广西壮族自治区","来宾":"广西壮族自治区","崇左":"广西壮族自治区","海口":"海南省","三亚":"海南省","三沙":"海南省","儋州":"海南省","重庆":"重庆市","成都":"四川省","自贡":"四川省","攀枝花":"四川省","泸州":"四川省","德阳":"四川省","绵阳":"四川省","广元":"四川省","遂宁":"四川省","内江":"四川省","乐山":"四川省","南充":"四川省","眉山":"四川省","宜宾":"四川省","广安":"四川省","达州":"四川省","雅安":"四川省","巴中":"四川省","资阳":"四川省","阿坝":"四川省","甘孜":"四川省","凉山":"四川省","贵阳":"贵州省","六盘水":"贵州省","遵义":"贵州省","安顺":"贵州省","毕节":"贵州省","铜仁":"贵州省","黔西南":"贵州省","黔东南":"贵州省","黔南":"贵州省","昆明":"云南省","曲靖":"云南省","玉溪":"云南省","保山":"云南省","昭通":"云南省","丽江":"云南省","普洱":"云南省","临沧":"云南省","楚雄":"云南省","红河":"云南省","文山":"云南省","西双版纳":"云南省","大理":"云南省","德宏":"云南省","怒江":"云南省","迪庆":"云南省","拉萨":"西藏自治区","日喀则":"西藏自治区","昌都":"西藏自治区","林芝":"西藏自治区","山南":"西藏自治区","那曲":"西藏自治区","阿里":"西藏自治区","西安":"陕西省","铜川":"陕西省","宝鸡":"陕西省","咸阳":"陕西省","渭南":"陕西省","延安":"陕西省","汉中":"陕西省","榆林":"陕西省","安康":"陕西省","商洛":"陕西省","兰州":"甘肃省","嘉峪关":"甘肃省","金昌":"甘肃省","白银":"甘肃省","天水":"甘肃省","武威":"甘肃省","张掖":"甘肃省","平凉":"甘肃省","酒泉":"甘肃省","庆阳":"甘肃省","定西":"甘肃省","陇南":"甘肃省","临夏":"甘肃省","甘南":"甘肃省","西宁":"青海省","海东":"青海省","海北":"青海省","黄南":"青海省","海南":"青海省","果洛":"青海省","玉树":"青海省","海西":"青海省","银川":"宁夏回族自治区","石嘴山":"宁夏回族自治区","吴忠":"宁夏回族自治区","固原":"宁夏回族自治区","中卫":"宁夏回族自治区","乌鲁木齐":"新疆维吾尔自治区","克拉玛依":"新疆维吾尔自治区","吐鲁番":"新疆维吾尔自治区","哈密":"新疆维吾尔自治区","昌吉":"新疆维吾尔自治区","博尔塔拉":"新疆维吾尔自治区","巴音郭楞":"新疆维吾尔自治区","阿克苏":"新疆维吾尔自治区","克孜勒":"新疆维吾尔自治区","喀什":"新疆维吾尔自治区","和田":"新疆维吾尔自治区","伊犁":"新疆维吾尔自治区","塔城":"新疆维吾尔自治区","阿勒泰":"新疆维吾尔自治区","天门":"湖北省","神农架":"湖北省","仙桃":"湖北省","昌江":"海南省","乐东":"海南省","潜江":"湖北省","屯昌县":"海南省","陵水黎族自治县":"海南省","四川":"四川省","定安县":"海南省","万宁":"海南省","琼海":"海南省","琼中黎族苗族自治县":"海南省","义乌":"浙江省"}'
    excludeInsurance:
      mapping: '{"辽宁省":"基本医疗保险费*职工基本医疗保险(单位缴纳)"}'
